version: '3.1'

services:

  ao_pdf:
    container_name: ao_pdf
    build: .
#    restart: always
    networks:
      - default
    ports:
      - 18001:8080
    stdin_open: true
    tty: true

networks:
  default:
    driver: bridge